language: python
dist: xenial

# only intended for Linux python3 jobs.
install: python3 -m pip install tox-travis
# only intended for Linux python3 jobs.
# Windows and MacOS will overwrite (Partly as tox-travis does not work on these two platforms)
# https://github.com/tox-dev/tox-travis/issues/133
script: python3 -m tox


before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi

jobs:
  include:
  # linux
  - python: '3.8'
  - python: '3.7'
  - python: '3.6.9'
  - python: '3.5'
  - python: '3.4.8'
  - python: '2.7.17'
    install: 'python -m pip install tox-travis'
    script: 'python -m tox'

  # osx python 3.8
  - name: "Python: 3.8"
    os: osx
    osx_image: xcode11
    language: shell
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Homebrew
    # switch to python 3.8
    addons:
      homebrew:
        update: true
    before_install:
      - pyenv install 3.8-dev
      - pyenv global 3.8-dev
    install: python3 -m pip install --user tox-travis
    # end switch
    script: python3 -m tox -e py38

  # osx python 3.7
  - name: "Python: 3.7"
    os: osx
    # xcode 11 image comes with python 3.7
    osx_image: xcode11
    # language: python will error
    language: shell
    before_script: python3 --version
    # weird permission error without --user
    install: python3 -m pip install --user tox-travis
    script: python3 -m tox -e py37

  # osx python 3.6.5
  - name: "Python: 3.6.5"
    os: osx
    osx_image: xcode9.4 # Python 3.6.5 running on macOS 10.13
    before_script: python3 --version
    language: shell
    install: python3 -m pip install --user tox-travis
    script: python3 -m tox -e py36

  # osx python 3.5
  - name: "Python: 3.5"
    os: osx
    osx_image: xcode11
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Homebrew
    language: shell
    # switch to python 3.5
    addons:
      homebrew:
        update: true
    before_install:
      - pyenv install 3.5.2
      - pyenv global 3.5.2
    install: python3 -m pip install --user tox-travis
    # end switch
    script: python3 -m tox -e py35

  # osx python 3.4
  - name: "Python: 3.4"
    os: osx
    osx_image: xcode11
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Homebrew
    language: shell
    # switch to python 3.4
    addons:
      homebrew:
        update: true
    before_install:
      - pyenv install 3.4.5
      - pyenv global 3.4.5
      - python3 -m pip install --user --upgrade setuptools
    install: python3 -m pip install --user tox-travis
    # end switch
    script: python3 -m tox -e py34

  # osx python 2.7.14
  - name: "Python: 2.7.14"
    os: osx
    osx_image: xcode9.3  # Python 2.7.14_2 running on macOS 10.13
    language: shell
    before_install:
      - python -m pip install --user --upgrade pip
      - python -m pip install --user --upgrade setuptools
    install: python -m pip install --user tox-travis
    script: python -m tox -e py27
    before_script: python --version

  # windows python 3.8
  - name: "Python: 3.8"
    os: windows
    # language: python will error
    language: shell
    # install python 3.8
    before_install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
    install: python -m pip install tox-travis
    # On Windows, python3 does not exist
    script: python -m tox -e py38
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

  # windows python 3.7
  - name: "Python: 3.7"
    os: windows
    # language: python will error
    language: shell
    # install python 3.7
    before_install:
      - choco install python --version 3.7.4
      - python -m pip install --upgrade pip
    install: python -m pip install tox-travis
    # On Windows, python3 does not exist
    script: python -m tox -e py37
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

  # windows python 3.6
  - name: "Python: 3.6"
    os: windows
    language: shell
    before_install:
      - choco install python --version 3.6.8
      - python -m pip install --upgrade pip
    install: python -m pip install tox-travis
    script: python -m tox -e py36
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

  # windows python 3.5
  - name: "Python: 3.5"
    os: windows
    language: shell
    before_install:
      - choco install python --version 3.5.4
      - python -m pip install --upgrade pip
    install: python -m pip install tox-travis
    script: python -m tox -e py35
    env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

  # windows python 3.4
  - name: "Python: 3.4"
    os: windows
    language: shell
    before_install:
      - choco install python --version 3.4.4.20180111
      - python -m pip install --upgrade pip
      - python -m pip install --upgrade setuptools # old setuptools does not recognize a bunch of keyword arguments in setup.py
    install: python -m pip install tox-travis
    script: python -m tox -e py34
    env: PATH=/c/Python34:/c/Python34/Scripts:$PATH

  # windows python 2.7
  - name: "Python: 2.7"
    os: windows
    language: shell
    before_install:
      - choco install python2
      - python -m pip install --upgrade pip
    install: python -m pip install tox-travis
    script: python -m tox -e py27
    env: PATH=/c/Python27:/c/Python27/Scripts:$PATH