language: python
dist: xenial

install: 'pipenv install --dev'
script: 'python -m pytest --cov=pipenv_setup'
after_success: 'codecov'

stages:
- test
- deploy
jobs:
  include:
  # linux
  - python: '3.7'
  - python: '3.6'

  # osx python 3.7
  - os: osx
    osx_image: xcode11
    language: shell
    before_install: python3 -m pip install pipenv
    install: pipenv install --dev
    script: pipenv run pytest --cov=pipenv_setup

  # osx python 3.6
  - os: osx
    osx_image: xcode11
    language: shell
    addons:
      homebrew:
        update: true
    before_install:
      - brew unlink python
      - brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
      - brew switch python 3.6.5_1
      - python3 -m pip install pipenv
    install: pipenv install --dev
    script: pipenv run pytest --cov=pipenv_setup

  # windows python 3.7
  - os: windows
    language: shell
    before_install:
      - choco install python
      - python -m pip install --upgrade pip
      - python -m pip install pipenv
    install: pipenv install --dev
    script: pipenv run pytest --cov=pipenv_setup
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

  # windows python 3.6
  - os: windows
    language: shell
    before_install:
      - choco install python --version 3.6.8
      - python -m pip install --upgrade pip
      - python -m pip install pipenv
    install: pipenv install --dev
    script: pipenv run pytest --cov=pipenv_setup
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

  - stage: deploy
    install: 'pipenv install --dev pipenv-setup'
    script: 'pipenv-setup sync'
    after_success: ''
    deploy:
      provider: pypi
      user: Madoshakalaka
      password:
        secure: KQizTecP7oH5S1zHk2dkFGqJHilEX43yitgGR91G1vmq4BBNRShu8Oq+uRpOX3Plz/oFyelnYhF987qq3xyg1E327ozX9EoQ+iDE3AKyBIBONUCAoe8pcG4XIwFsjdmOkw9ODeKq8VU8t+KSAvIPIEd27G6N6WQ+DVOcoyIn0uJsCB0jX32wqaCQO8yTf1A/qWVzYnt8aqBXToDiC0XprrodMgvrTExyhBLW5Y7zuiNgfGb6HtRHAa9nvoO3/V8Jn2yXlv/uzE0rsVll+w0mxz/fYRkjZIfk7ju8L4b49+gu/onG827pOwQkfswUwb3QsXRR4PugmTyNGVuX5svxT22K+kYZaJn646X/nkljYJMhYNjbtuSlZcfZyg8QEJ1jNNtWW48Gt5yOTc1HPdggOig9hygj+ctc/TeIEKzaCMx9S184+Sz8LzNSiHTsmde0SxgIcS/QM8+5xdJ2yr917qhqh8iiiBeD58bISKGk+cEQNqha1aIVU4G9JhQsknaKUDUnQ7sSiO3dUGOJqGpuDQzJr5O4TEC2Rf05VzLSpkfTTjAhIVTH4gE3EcEbGQlaa3VHZvftdFmAHEu9nueC9dolSFEwqu/yf+bv3LGBskEbDUQir21RbX3axuS9NvaZX33vNlyLFmI41Or2iaOopgJeHlhlxLESTX5EhjNmpf0=
      on:
        tags: true